version: '3'

services:
  web:
    build: .
    hostname: fastapi
    healthcheck:
      interval: 5m
      timeout: 30s
      retries: 3
    ports:
      - '5000:8080'
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy

  database:
    hostname: fastapi_db
    container_name: fastapi_db
    image: postgres:latest
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 30s
      retries: 6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql
    restart: always
