name: Run Python code and docstyle linters

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python libs used to check code quality.
        run: python3 -m pip install -r requirements-dev.txt

      - name: Lint Python code
        run: |
             python -m mypy ./src
             python -m flake8 ./src
             python -m pylint ./src
             python -m bandit ./src
             python -m pydocstyle ./src
